{
  "name": "skytech",
  "static_sites": [],
  "services": [
    {
      "name": "web",
      "run_command": "cd admin && PORT=8080 npm start",
      "build_command": "npm run build && cd admin && npm run build",
      "environment_slug": "node-js",
      "http_port": 8080
    }
  ]
}
