name: skytech
services:
- name: web
  github:
    repo: danielagblo/skytech
    branch: main
  build_command: npm run build && cd admin && npm run build
  run_command: cd admin && npm start
  environment_slug: node-js
  envs:
  - key: PORT
    value: "8080"

